//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sa41team7_logicuniversity_stationery
{
    using System;
    using System.Collections.Generic;
    
    public partial class collectionpoint
    {
        public collectionpoint()
        {
            this.departments = new HashSet<department>();
        }
    
        public string collectionpointname { get; set; }
        public string clerkID { get; set; }
        public string collectiontime { get; set; }
    
        public virtual staff staff { get; set; }
        public virtual ICollection<department> departments { get; set; }
    }
}
