//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sa41team7_logicuniversity_stationery
{
    using System;
    using System.Collections.Generic;
    
    public partial class disbursement
    {
        public disbursement()
        {
            this.disbursementdetails = new HashSet<disbursementdetail>();
        }
    
        public int disbursementID { get; set; }
        public System.DateTime createdate { get; set; }
        public string clerkID { get; set; }
        public string departmentID { get; set; }
        public string repID { get; set; }
        public string status { get; set; }
    
        public virtual department department { get; set; }
        public virtual ICollection<disbursementdetail> disbursementdetails { get; set; }
        public virtual staff staff { get; set; }
        public virtual staff staff1 { get; set; }
    }
}
