//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sa41team7_logicuniversity_stationery
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LSEntities : DbContext
    {
        public LSEntities()
            : base("name=LSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adjustvoucher> adjustvouchers { get; set; }
        public virtual DbSet<adjustvoucherdetail> adjustvoucherdetails { get; set; }
        public virtual DbSet<catalogue> catalogues { get; set; }
        public virtual DbSet<collectionpoint> collectionpoints { get; set; }
        public virtual DbSet<delegateauthority> delegateauthorities { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<disbursement> disbursements { get; set; }
        public virtual DbSet<disbursementdetail> disbursementdetails { get; set; }
        public virtual DbSet<itemprice> itemprices { get; set; }
        public virtual DbSet<mobilenotification> mobilenotifications { get; set; }
        public virtual DbSet<podetail> podetails { get; set; }
        public virtual DbSet<purchaseorder> purchaseorders { get; set; }
        public virtual DbSet<requisition> requisitions { get; set; }
        public virtual DbSet<requisitiondetail> requisitiondetails { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<stockcard> stockcards { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Retrieval_Form_View> Retrieval_Form_View { get; set; }
    }
}
