//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sa41team7_logicuniversity_stationery
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseorder
    {
        public purchaseorder()
        {
            this.podetails = new HashSet<podetail>();
        }
    
        public int poID { get; set; }
        public string supplierID { get; set; }
        public string clerkID { get; set; }
        public System.DateTime orderdate { get; set; }
        public System.DateTime expecteddate { get; set; }
        public double totalamount { get; set; }
        public string approverid { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<podetail> podetails { get; set; }
        public virtual staff staff { get; set; }
        public virtual staff staff1 { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
