//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sa41team7_logicuniversity_stationery
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisition
    {
        public requisition()
        {
            this.requisitiondetails = new HashSet<requisitiondetail>();
        }
    
        public int requestID { get; set; }
        public string departmentID { get; set; }
        public string userID { get; set; }
        public System.DateTime requestdate { get; set; }
        public string status { get; set; }
        public string approverID { get; set; }
        public string comment { get; set; }
        public string type { get; set; }
    
        public virtual department department { get; set; }
        public virtual ICollection<requisitiondetail> requisitiondetails { get; set; }
        public virtual staff staff { get; set; }
        public virtual staff staff1 { get; set; }
    }
}
