//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sa41team7_logicuniversity_stationery
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.adjustvouchers = new HashSet<adjustvoucher>();
            this.adjustvouchers1 = new HashSet<adjustvoucher>();
            this.collectionpoints = new HashSet<collectionpoint>();
            this.delegateauthorities = new HashSet<delegateauthority>();
            this.delegateauthorities1 = new HashSet<delegateauthority>();
            this.departments = new HashSet<department>();
            this.departments1 = new HashSet<department>();
            this.departments2 = new HashSet<department>();
            this.disbursements = new HashSet<disbursement>();
            this.disbursements1 = new HashSet<disbursement>();
            this.mobilenotifications = new HashSet<mobilenotification>();
            this.mobilenotifications1 = new HashSet<mobilenotification>();
            this.purchaseorders = new HashSet<purchaseorder>();
            this.purchaseorders1 = new HashSet<purchaseorder>();
            this.requisitions = new HashSet<requisition>();
            this.requisitions1 = new HashSet<requisition>();
        }
    
        public string userID { get; set; }
        public string name { get; set; }
        public string departmentid { get; set; }
        public string role { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<int> phone { get; set; }
    
        public virtual ICollection<adjustvoucher> adjustvouchers { get; set; }
        public virtual ICollection<adjustvoucher> adjustvouchers1 { get; set; }
        public virtual ICollection<collectionpoint> collectionpoints { get; set; }
        public virtual ICollection<delegateauthority> delegateauthorities { get; set; }
        public virtual ICollection<delegateauthority> delegateauthorities1 { get; set; }
        public virtual ICollection<department> departments { get; set; }
        public virtual ICollection<department> departments1 { get; set; }
        public virtual ICollection<department> departments2 { get; set; }
        public virtual ICollection<disbursement> disbursements { get; set; }
        public virtual ICollection<disbursement> disbursements1 { get; set; }
        public virtual ICollection<mobilenotification> mobilenotifications { get; set; }
        public virtual ICollection<mobilenotification> mobilenotifications1 { get; set; }
        public virtual ICollection<purchaseorder> purchaseorders { get; set; }
        public virtual ICollection<purchaseorder> purchaseorders1 { get; set; }
        public virtual ICollection<requisition> requisitions { get; set; }
        public virtual ICollection<requisition> requisitions1 { get; set; }
    }
}
