//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sa41team7_logicuniversity_stationery
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.itemprices = new HashSet<itemprice>();
            this.purchaseorders = new HashSet<purchaseorder>();
        }
    
        public string supplierID { get; set; }
        public string name { get; set; }
        public string contactname { get; set; }
        public Nullable<int> phone { get; set; }
        public Nullable<int> fax { get; set; }
        public string address { get; set; }
        public string gst { get; set; }
    
        public virtual ICollection<itemprice> itemprices { get; set; }
        public virtual ICollection<purchaseorder> purchaseorders { get; set; }
    }
}
